### ISSUE TITLE
[sugestões] Curso front-end engineer

### ISSUE THREAD

**Issue by woliveiras** [woliveiras/twitch#1]
Utilize esta issue para sugerir tópicos que você acha importantes para o curso. :D

**Comment by woliveiras** [comment]
Em um bate papo na Twitch, chegamos na seguinte lista de tópicos que a comunidade gostaria de ver:

## O que é a base para desenvolvimento frontend?

- como funciona a internet
- trabalhando com Ajax com JS puro
    - verbos HTTP
- como debugar código no navegador
    - como analisar o HTML
    - como verificar as requisições
    - performance
- acessibilidade
    - semantica
- SEO
- Layout com CSS
    - design vs recursos do CSS
    - especificidade CSS
    - organização de código CSS
- responsividade com CSS puro
    - desenvolvimento mobile first
- retrocompatibilidade do código client side

## Quais são os conceitos fundamentais que toda pessoa frontend deveria conhecer?

Design Patterns
Testes de Software
Estruturas de Dados e Algoritmos
Verbos HTTP
Arquitetura de Software
Performance
Acessibilidade
Participar de comunidades
Conceitos básicos de UX

**Comment by spacexjedi** [comment]
Esse é o curriculo da [codecademy](https://www.codecademy.com/learn/paths/web-development) para o web path,
estava com três meses gratuitos para todos com um e-mail educacional.  

1 **Learn HTML**
Get started as a web developer by learning the basics of HTML, the essential language of the web.

2 **Styling a Website**
Learn and practice the fundamentals of CSS to add beautiful styling to your webpages.

3 **Getting Started with JavaScript**
Learn the fundamentals of JavaScript: syntax, variables, conditionals, and functions.

4 **Getting More Advanced with Design**
Learn CSS techniques for more interesting sites: display & positioning, colors, typography, responsive design, and flexbox.

5 **JavaScript: Arrays, Loops, and Objects**
Discover more JavaScript techniques and features including arrays, looping, and objects.

6 **Building Interactive JavaScript Websites**
Learn the Document Object Model, the interface between JavaScript and HTML elements, and combine HTML, CSS, and JavaScript into exciting interactive sites!

7 **Intermediate JavaScript**
Learn more techniques to extend your JavaScript knowledge including reusable classes, splitting code into modules, and making HTTP requests.

8 **Learn the Command Line**
Discover the power of this simple yet essential text-based tool and increase your productivity as a developer.

9 **Learn Git**
Learn to save and manage different versions of your code projects with this essential tool.

10 **Building Front-end Applications with React**
Learn to build dynamic and powerful web apps using React.js, a component-based front-end framework.

11 **JavaScript Back-End Development**
Learn how to create back-end servers and APIs in JavaScript using the popular Express.js framework.

12 **SQL and Databases for Web Development**
Learn the SQL fundamentals needed to be a successful full-stack web developer.

13 **Building a Persistent API**
Learn the Node-SQLite to connect JS and SQL in web apps, and build your first fully-integrated back-end application.

14 **Test-Driven Development with JavaScript**
Master the fundamentals of Test-Driven Development to create reliable full-stack JavaScript web applications.

**Comment by woliveiras** [comment]
Muito obrigado pela participação, galera

O curso começou e vamos lançar a bronca nessas sugestões, ein! :D
